export const CANTIDAD_ATENCIONES = 400000;
export const CANTIDAD_CITAS = 600000;
export const CANTIDAD_DOCTORES = 10;
export const CANTIDAD_PACIENTES = 50000;	
export const CANTIDAD_CONTACTOS_EMERGENCIA = 40000;
export const CANTIDAD_SERVICIOS = 38;
export const CANTIDAD_TIPOS_ATENCION = 3;
export const CANTIDAD_ESTADOS_ATENCION = 5;
export const CANTIDAD_TIPOS_PACIENTE = 2;
export  const CANTIDAD_ESPECIALIDADES = 6;
export const CANTIDAD_ESTADOS_CITA = 5;
export const CANTIDAD_INSTITUCIONES_EXTERNAS = 6;
export const CANTIDAD_REFERENCIAS = 150000;

export const MAX_FRAME_SIZE = 1000;