INSERT INTO ESTADO_ATENCION(Estado) VALUES ('SIN COMPLICACIONES'), ('HUBO COMPLICACIONES POST-OPERATORIAS'), ('HUBO COMPLICACION INTEROPERATORIA'), ('INCOMPLETO');
GO

INSERT INTO TIPO_ATENCION(TipoAtencion) VALUES ('EMERGENCIA'), ('CONSULTA'), ('QUIRURGICO');
GO

INSERT INTO TIPO_SERVICIO(TipoServicio) VALUES ('DIAGNOSTICO'),('PROCEDIMIENTO ESPECIAL'),('CIRUGIA');
GO

INSERT INTO ESTADO_CITA(EstadoCita) VALUES ('PENDIENTE'), ('ATENDIDA'), ('CANCELADA'), ('NO ASISTIO'), ('REPROGRAMADA');
GO


INSERT INTO SERVICIO(Descripcion ,IdTipoServicio, CostoActual) VALUES ('OFTAMOLOG�A GENERAL', 1, 50), ('OFTAMOLOGIA PEDIATRICA', 1, 40), ('REFRACCI�N', 1, 50), ('RETINA Y VITREO', 1, 150), ('GLAUCOMA', 1, 60), ('ESTRABISMO', 1, 100), ('CORNEA', 1, 120), ('CATARATA', 1, 100), ('CARDIOLOGO', 1, 50), ('UVEITIS', 1, 70), ('OCULO PLASTIA', 1, 150), ('PATOLOGIA', 1, 150), ('NEURO OFTAMOLOGIA', 1, 200), ('VIA LAGRIMAL', 1, 120), ('CAMPA�A PREV. DE LA CEGUERA', 1, 0), ('CONTACTOLOG�A', 1, 60), ('BAJA VISION', 1, 70);
GO

INSERT INTO SERVICIO(Descripcion,IdTipoServicio, CostoActual) VALUES ('CURVAS DE PRESION', 2, 50), ('RETINOGRAFIA', 2, 60),('CAMPO VISUAL COMPUT.', 2, 10),('ANGIOGRAFIA', 2, 20),('BIOMETRIA', 2, 30),('CAPSULOTOMIA', 2, 40),('ECOGRAFIA', 2, 30),('IRIDOPLASTIA', 2, 20),('IRIDOTOMIA', 2, 40),('LASER GLAUCOMA', 2, 100),('LASER RETINAL', 2, 120),('MICROSCOPIA ESPECULAR', 2, 40),('PAQUIMETRIA', 2, 20),('TOPOGRAFIA CORNEAL', 2, 90);
GO

INSERT INTO SERVICIO(Descripcion, IdTipoServicio, CostoActual) VALUES ('CRISTALINO',3, 200),('CONJUNTIVA',3, 300),('ORBITA PARPADO',3, 150),('GLAUCOMA',3, 300),('ESTRABISMO',3, 500),('GLOBO OCULAR',3, 300),('RETINA Y VITREO',3, 500);
GO

INSERT INTO TIPO_PACIENTE(TipoPaciente) values ('EXTERNO'), ('SIS');
GO

INSERT INTO ESPECIALIDAD(Especialidad) VALUES ('GENERAL'), ('RETINA'),('GLAUCOMA'),('PEDIATR�A'),('OCULOPLASTIA'),('NEUROLOGIA');
GO

INSERT INTO INSTITUCION_EXTERNA(Institucion) VALUES ('Hospital Regional Docente de Trujillo'), ('Hospital Belén'), ('Hospital Albrecht'), ('Hospital La Noria'),('Clínicas'), ('Otros');
GO